export const SESSION = 'SESSION';
export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const SIGNUP_LOADING_FALSE = 'SIGNUP_LOADING_FALSE';

export const MARKET_DATA = 'MARKET_DATA';
export const MARKET_DATA_LOADING = 'MARKET_DATA_LOADING';

export const TICKER_DATA = 'TICKER_DATA';
export const TICKER_DATA_LOADING = 'TICKER_DATA_LOADING';

export const NEWS_DATA = 'NEWS_DATA';
export const MARKET_LIST = 'MARKET_LIST';
export const GET_SINGLE_MARKET = 'GET_SINGLE_MARKET';

export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_LOADING = 'CREATE_ORDER_LOADING';

export const GET_ORDER = 'GET_ORDER';

export const MARKET_NEWS = 'MARKET_NEWS';
export const GET_ORDER_HISTORY = 'GET_ORDER_HISTORY';
