export const SESSION = 'SESSION';
export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const SIGNUP_LOADING_FALSE = 'SIGNUP_LOADING_FALSE';

export const MARKET_DATA = 'MARKET_DATA';
export const MARKET_DATA_LOADING = 'MARKET_DATA_LOADING';
