export const SESSION = 'SESSION';
export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const SIGNUP_LOADING_FALSE = 'SIGNUP_LOADING_FALSE';

export const MARKET_DATA = 'MARKET_DATA';
export const MARKET_DATA_LOADING = 'MARKET_DATA_LOADING';

export const TICKER_DATA = 'TICKER_DATA';
export const TICKER_DATA_LOADING = 'TICKER_DATA_LOADING';

export const NEWS_DATA = 'NEWS_DATA';
export const MARKET_LIST = 'MARKET_LIST';
export const GET_SINGLE_MARKET = 'GET_SINGLE_MARKET';

export const CREATE_ORDER = 'CREATE_ORDER';
export const DEPOSITE_WITHDRAW_ORDER = 'DEPOSITE_WITHDRAW_ORDER';
export const ADD_ALERT_ORDER = 'ADD_ALERT_ORDER';
export const CREATE_ORDER_LOADING = 'CREATE_ORDER_LOADING';

export const GET_ORDER = 'GET_ORDER';

export const MARKET_NEWS = 'MARKET_NEWS';
export const GET_ORDER_HISTORY = 'GET_ORDER_HISTORY';

export const WATCHLIST_MARKETS = 'WATCHLIST_MARKETS';

export const ALL_NOTIFICATIONS = 'ALL_NOTIFICATIONS';
export const ALL_ALERTS = 'ALL_ALERTS';
export const LATEST_ALERTS = 'LATEST_ALERTS';
export const GET_ASSETS = 'GET_ASSETS';

export const CHANGEPASSWORD_LOADING = 'CHANGEPASSWORD_LOADING';
export const CHANGEPASSWORD_MSG = 'CHANGEPASSWORD_MSG';
export const DEPOSITE_MSG = 'DEPOSITE_MSG';
export const NOTIFICATION_LOADING = 'NOTIFICATION_LOADING';
export const DEPOSITEWITHDRAW = 'DEPOSITEWITHDRAW';
export const CURRENCY_FACTOR = 'CURRENCY_FACTOR';
export const CURRENT_CURRENCY_FACTOR = 'CURRENT_CURRENCY_FACTOR';
export const TICKER_GRAPH_DATA = 'TICKER_GRAPH_DATA';
export const CREATE_CALL_REQ = 'CREATE_CALL_REQ';

export const ASSETS_DATA_LOADING = 'ASSETS_DATA_LOADING';
export const ORDER_DATA_LOADING = 'ORDER_DATA_LOADING';
export const TRANSACTION_DATA_LOADING = 'TRANSACTION_DATA_LOADING';




